version: '3.7'

services:
    
    apache:
        build:
        image: apache2
        ports:
            - "80:8080"
        volumes:
            - .:/var/www/html
        restart: always
        links:
            - mysql 
            
            
    mysql:
        image: mysql:5.7
        ports: 
            - "3306:3306"
        environment:
            MYSQL_DATABASE: "yankovyi"
            MYSQL_USER: "yankovyi"
            MYSQL_PASSWORD: "bayda"
            MYSQL_ROOT_PASSWORD: "baydaroot"
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - persistent:/var/lib/mysql
        networks:
            - default
    
    
